# Site settings
title: Julio Valcarcel
description: 'Security, Technology, and anything I else find interesting'
url: 'https://juliovalcarcel.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Julio Valcarcel'
  email: contact@juliovalcarcel.com
  twitter_username: jvalcarcel
  github_username:  juliovalcarcel
  linkedin_username:  juliovalcarcel

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'vendor']
